version: '3.8'

services:
  web:
    build: .
    container_name: mon_app
    ports:
      - "5000:5000"
    networks:
      - mon_reseau
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ma_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass123
    volumes:
      - mon_volume:/var/lib/mysql
    networks:
      - mon_reseau

volumes:
  mon_volume:

networks:
  mon_reseau:
